# Generated by Django 3.0.4 on 2020-04-16 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(default='Untitled', max_length=120)),
                ('content', models.TextField(default='Description Needed')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(default='CAS', max_length=40)),
                ('tags', models.TextField(default='No Tags')),
                ('contact_info', models.EmailField(default=False, max_length=60, verbose_name='email')),
                ('eventType', models.CharField(choices=[('F', 'Fair'), ('C', 'Culture'), ('E', 'Entertainment'), ('GEN', 'General Meeting')], default='GEN', max_length=20)),
                ('alreadyHappened', models.BooleanField(default=True)),
                ('banner', models.ImageField(default='default.jpg', upload_to='')),
                ('author', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
