# Generated by Django 3.0.4 on 2020-04-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200426_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='event_banner'),
        ),
    ]
