# Generated by Django 3.0.4 on 2020-04-27 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_club_events'),
        ('events', '0003_auto_20200426_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Events', to='organizations.Club'),
        ),
    ]
