# Generated by Django 3.0.4 on 2020-04-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_club_events'),
        ('events', '0004_auto_20200427_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='affiliation_id',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='Events', to='organizations.Club'),
        ),
        migrations.AlterField(
            model_name='event',
            name='affiliation',
            field=models.TextField(default='No Affiliation'),
        ),
    ]
