# Generated by Django 3.0.4 on 2020-04-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200418_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventAffiliation',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
