# Generated by Django 3.0.4 on 2020-04-28 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200427_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='affiliation_id',
            new_name='affiliation_number',
        ),
    ]
