# Generated by Django 3.0.4 on 2020-04-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200418_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='alreadyHappened',
        ),
        migrations.AddField(
            model_name='event',
            name='eventTime',
            field=models.CharField(default='12:00:00', max_length=20),
        ),
    ]
