# Generated by Django 3.0.4 on 2020-04-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200422_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.TextField(default='March 20, 2018'),
        ),
    ]
