# Generated by Django 3.0.4 on 2020-05-01 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Untitled', max_length=120)),
                ('affiliation', models.TextField(default='No Affiliation')),
                ('picture', models.ImageField(blank=True, default='default.jpg', upload_to='event_banner')),
                ('description', models.TextField(default='Description Needed')),
                ('date', models.TextField(default='March 20, 2018')),
                ('time', models.TextField(default='12:00:00', max_length=60)),
                ('location', models.TextField(default='CAS', max_length=40)),
                ('type', models.TextField(default='GENERAL_MEETING', max_length=20)),
                ('tags', models.TextField(default='No Tags')),
                ('contact', models.EmailField(default=False, max_length=60, verbose_name='email')),
                ('connection', models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='Events', to='organizations.Club')),
            ],
        ),
    ]
