# Generated by Django 3.0.4 on 2020-04-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Untitled', max_length=120)),
                ('affiliation', models.CharField(default='None', max_length=30)),
                ('picture', models.ImageField(default='default.jpg', upload_to='')),
                ('description', models.TextField(default='Description Needed')),
                ('date', models.TextField(default='March 20, 2018')),
                ('time', models.CharField(default='12:00:00', max_length=20)),
                ('location', models.CharField(default='CAS', max_length=40)),
                ('type', models.CharField(default='GENERAL_MEETING', max_length=20)),
                ('tags', models.TextField(default='No Tags')),
                ('contact', models.EmailField(default=False, max_length=60, verbose_name='email')),
            ],
        ),
    ]
