# Generated by Django 3.0.4 on 2020-05-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
        ('events', '0002_event_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='rsvp', to='userAccount.Profile'),
        ),
    ]
