# Generated by Django 3.0.4 on 2020-04-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200418_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventType',
            field=models.CharField(default='GENERAL_MEETING', max_length=20),
        ),
    ]
