# Generated by Django 3.0.4 on 2020-04-28 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200427_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='affiliation_number',
            new_name='connection',
        ),
    ]
