# Generated by Django 3.0.4 on 2020-05-01 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('organizations', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(default=False, max_length=60, verbose_name='email')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('year', models.IntegerField(default=2020)),
                ('major', models.CharField(default='Undeclared', max_length=255)),
                ('introduction', models.TextField(default='None')),
                ('schedule', jsonfield.fields.JSONField(default={})),
                ('tags', models.TextField(default='No Tags')),
                ('events', models.ManyToManyField(blank=True, related_name='favoriteEvents', to='events.Event')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='subscribedClubs', to='organizations.Club')),
            ],
        ),
    ]
