# Generated by Django 3.0.4 on 2020-04-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0003_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
