# Generated by Django 3.0.4 on 2020-04-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20200426_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.TextField(default='CAS 211'),
        ),
        migrations.AlterField(
            model_name='club',
            name='time',
            field=models.TextField(default='12:00:00'),
        ),
    ]
