# Generated by Django 3.0.4 on 2020-04-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200426_1913'),
        ('organizations', '0005_auto_20200426_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='events',
            field=models.ManyToManyField(to='events.Event'),
        ),
    ]
