# Generated by Django 3.0.4 on 2020-04-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('picture', models.ImageField(default='default.jpg', upload_to='')),
                ('description', models.TextField(default='Are there any descriptions?')),
                ('requirements', models.TextField(default='None')),
                ('eboard', models.TextField(default='Bob Dole')),
                ('time', models.CharField(default='12:00:00', max_length=20)),
                ('location', models.CharField(default='CAS 211', max_length=20)),
                ('contact', models.TextField(default='busmashbrosociety@gmail.com')),
                ('tags', models.TextField(default='No Tags')),
            ],
        ),
    ]
