# Generated by Django 3.0.4 on 2020-05-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='userAccount.Profile'),
        ),
    ]
