# Generated by Django 3.0.4 on 2020-04-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.TextField(default='CAS 211', max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='time',
            field=models.TextField(default='12:00:00', max_length=20),
        ),
    ]
