# Generated by Django 3.0.4 on 2020-04-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200426_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='organization_banner'),
        ),
    ]
