# Generated by Django 3.0.4 on 2020-04-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_remove_club_clubmeetingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='clubRequirements',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='club',
            name='clubDescription',
            field=models.TextField(default='No Description'),
        ),
        migrations.AlterField(
            model_name='club',
            name='clubPersonOfContact',
            field=models.TextField(default='ryli1998@bu.edu'),
        ),
    ]
