# Generated by Django 3.0.4 on 2020-04-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_club_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='events',
        ),
    ]
