# Generated by Django 3.0.4 on 2020-04-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20200427_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='tags',
            field=models.TextField(default='No Tags'),
        ),
    ]
