# Generated by Django 3.0.4 on 2020-04-18 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubId', models.CharField(max_length=10)),
                ('clubName', models.CharField(max_length=30)),
                ('clubPicture', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('clubDescription', models.TextField()),
                ('clubMeetingTime', models.TimeField(default=datetime.datetime(2020, 4, 18, 20, 19, 34, 814675, tzinfo=utc))),
                ('clubLocation', models.CharField(default='CAS 211', max_length=20)),
                ('clubPersonOfContact', models.TextField(default='Adam Garfield')),
                ('clubTags', models.TextField(default='No Tags')),
            ],
        ),
    ]
