# Generated by Django 3.0.4 on 2020-04-18 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200418_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='clubMeetingTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 18, 20, 26, 23, 437769, tzinfo=utc)),
        ),
    ]
