# Generated by Django 3.0.4 on 2020-04-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200418_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='clubMeetingTime',
        ),
    ]
