# Generated by Django 3.0.4 on 2020-04-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20200422_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='clubDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='clubLocation',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='clubName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='clubPicture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='clubRequirements',
            new_name='requirements',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='clubTags',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='club',
            name='clubId',
        ),
        migrations.RemoveField(
            model_name='club',
            name='clubPersonOfContact',
        ),
        migrations.AddField(
            model_name='club',
            name='contact',
            field=models.TextField(default='busmashbrosociety@gmail.com'),
        ),
        migrations.AddField(
            model_name='club',
            name='eboard',
            field=models.TextField(default='Bob Dole'),
        ),
        migrations.AddField(
            model_name='club',
            name='time',
            field=models.CharField(default='12:00:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
