# Generated by Django 3.0.4 on 2020-04-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20200422_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(default='Are there any descriptions?'),
        ),
    ]
