# Generated by Django 3.0.4 on 2020-04-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_auto_20200413_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=False, max_length=60, verbose_name='email'),
        ),
    ]
