# Generated by Django 3.0.4 on 2020-04-30 02:32

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0004_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='schedule',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
