# Generated by Django 3.0.4 on 2020-04-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0005_profile_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduction',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(default='Undeclared', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
