# Generated by Django 3.0.4 on 2020-04-26 01:08

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0005_auto_20200425_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='schedule',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
