# Generated by Django 3.0.4 on 2020-04-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0006_auto_20200425_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
