# Generated by Django 3.0.4 on 2020-04-30 07:44

from django.db import migrations
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0006_auto_20200430_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credentials',
            field=oauth2client.contrib.django_util.models.CredentialsField(null=True),
        ),
    ]
