# Generated by Django 3.0.4 on 2020-04-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0007_auto_20200425_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='schedule',
        ),
    ]
